### ISSUE TITLE
sanitize tokens that are empty strings?

### ISSUE THREAD

**Issue by kbvernon** [R-ArcGIS/arcgisutils#5]
When `Sys.getenv("ARCGIS_TOKEN")` returns an empty string, this will sometimes cause HTTP 498 "invalid token" error. Proposed solution is to empty the token with NULL.

**Comment by JosiahParry** [comment]
reprex: 
```r
furl <- "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI_NAD83/MapServer/1"
arc_open(furl)

arc_open(furl, token = NULL)
```
